credentials:
  username:
    anuoluwapods:
      email: ifeoluwapobalogun1@gmail.com
      name: Anuoluwapo Balogun
      password: 'Creativeart1.' # To be replaced with hashed password
 
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - designegycreatives@gmail.com
