deta_key = "a0r5asax_L3B8ic9Q7yjgKU8dAiwk86NWWakND4K3"

deta_key1 = "a0r5asax_wNLXBrZfZortnCwftRpwmHBcvqNMxTHk"

deta_key2 = "a0r5asax_QPgkn79gtuVd8DsxkW38AqzPnHasse2t"

deta_key3 = "a0r5asax_H5SJoqdu4rn6fRU3YQH1YLLBMtTrdgoN"
